### ISSUE TITLE
package.lock.json

### ISSUE THREAD

**Issue by ashkaps** [syncfusion/ej2-showcase-angular-webmail#2]
Hi, is it possible to share package.lock.json?

**Comment by SowmiyaPadmanaban** [comment]
Hi AK,

 

We have checked your requirement. Please download the below GitHub repository and run the npm install command. It automatically creates the package.lock  json file.

 

https://github.com/syncfusion/ej2-showcase-angular-webmail

 

Please let us know, if you need any further assistance.

 

Regards,

Sowmiya.P

**Comment by ashkaps** [comment]
Hey @SowmiyaPadmanaban thanks for the quick response. 
The problem I ran into was that the angular version and other deps are deprecated / incompatible now. So I am unable to build and run the project locally. 
My aim is to incorporate this with my existing angular project which is built on angular 8. I did try to update everything to the latest compatible versions but that didn't help me either. 
Any suggestions ?

**Comment by Indhumathy-Loganathan** [comment]
Hi AK,

Thank you for your patience.

We have prepared a webmail showcase sample in angular 8 version. Please find the sample from the below link.

https://www.syncfusion.com/downloads/support/directtrac/general/ze/Webmail444138951

Run npm install to create package.lock.json file and ng serve to run the sample.

Please let us know, if you need any further assistance.

Regards,
Indhumathy L

**Comment by ashkaps** [comment]
Hi @Indhumathy-Loganathan , thank you for making this happen.

**Comment by Indhumathy-Loganathan** [comment]
Hi @ashkaps, Most welcome. We are glad to hear that the issue has been solved.
